In [3]:
import numpy as np

## Creating Arrays

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.full(5,8.99)


array([8.99, 8.99, 8.99, 8.99, 8.99])

In [12]:
pylist = [1,2,3,4,5,6]
a=np.array(pylist)
a #python list to array

array([1, 2, 3, 4, 5, 6])

In [13]:
#now to access a number from the array 
a[5]

np.int64(6)

In [65]:
np.arange(12, 20) #excludes end number 
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
np.linspace(0,23,5) #inclusive of both start and end. 

array([ 0.  ,  5.75, 11.5 , 17.25, 23.  ])

## Multi-dimensional Arrays

In [28]:
# most of the same functions as above, but with 2 instead of 1 parameter, (depicted by a set) e.g. 

np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
n=np.array([
    [1,2,3],
    [4,5,6]
]) #generates a 2D matrix

n

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
n[1][1]

# or you can also do the below

n[1,1]

np.int64(5)

In [37]:
n[1,0]=99
n

array([[ 1,  2,  3],
       [99,  5,  6]])

In [40]:
n[1] = [0,0,0]
n                #to access and update individual rows

array([[1, 2, 3],
       [0, 0, 0]])

In [46]:
n[:, 2]         #to access individual columns

array([3, 0])

In [48]:
# n == n[:] will yield the same result

array([[1, 2, 3],
       [0, 0, 0]])

## Randomly Generated Arrays

In [56]:
# to generate random arrays we use np.random, e.g. 

np.random.rand(4,4) # where param 1 = no. of rows
                     # param 2 = no. of columns

# to retain the numbers, and generate fixed vales each time, set seed like below:

np.random.seed(8)
np.random.rand(2,2)

array([[0.8734294 , 0.96854066],
       [0.86919454, 0.53085569]])

In [60]:
# new way to use random - rng = np.random.default_rng(seed=42)

rng=np.random.default_rng(seed=42)
rng.integers(1, 10, 5)

array([1, 7, 6, 4, 4])

In [61]:
# if you want a list/array/matrix of negative numbers use randn 

np.random.randn(2,2)

array([[-1.94697031, -1.38634953],
       [-2.29649157,  2.4098343 ]])

In [62]:
# random integers but within a set start and end 

np.random.randint(low=10, high=100, size=(5,2))

array([[19, 71],
       [25, 69],
       [28, 24],
       [66, 19],
       [61, 78]])

## Element Wise Operators

In [64]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
#to add/sub/multiply/divide you can just do the below:

a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
a - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [76]:
b=((a + 7)*4/10)**2 
b

array([ 7.84, 10.24, 12.96, 16.  , 19.36, 23.04, 27.04, 31.36, 36.  ,
       40.96])

In [75]:
#the need for loops here is eliminated

In [77]:
a+b

array([ 7.84, 11.24, 14.96, 19.  , 23.36, 28.04, 33.04, 38.36, 44.  ,
       49.96])

## Comparison Operations

In [81]:
print(a)
a>4

[0 1 2 3 4 5 6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [82]:
a == b/10

array([False, False, False, False, False, False, False, False, False,
       False])

In [83]:
a == 3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [84]:
a-a == b-b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [89]:
a[a>b-100]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Converting Numpy Array to Dataframe and vice versa

In [112]:
import pandas as pd 

n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
df=pd.DataFrame(n, columns=["col1", "col2", "col3"])
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [94]:
n_arr=df.to_numpy()
n_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Summarizing Operations 

In [99]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.std())

0
9
45
4.5
2.8722813232690143


In [102]:
# to round off the standard deviation you can use np.round()

np.round(a.std(),4)

np.float64(2.8723)

In [114]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
new_n=n[:2, 1:].copy()

In [119]:
print(new_n.min())
print(new_n.max())
print(new_n.sum())
print(new_n.mean())
print(new_n.std())

2
6
16
4.0
1.5811388300841898
